name: polymer_elements_demos
version: 0.1.0
author: Polymer.dart Authors <guenter@gzoechbauer.com>
description: Polymer polymer_elements for Dart examples.
homepage: https://github.com/bwu-dart/polymer_elements_demos
environment:
  sdk: '>=1.12.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  polymer: ^1.0.0-rc.4
  polymer_elements: ^1.0.0-rc.2
  polymer_interop: ^1.0.0-rc.3
  reflectable: ^0.3.2
  web_components: ^0.12.0
dev_dependencies:
  github: '>=2.2.3+1 <3.0.0'
  path: '>=1.3.6 <2.0.0'
  test: ^0.12.0
  quiver: '>=0.21.4 <0.22.0'
  crypto: '>=0.9.1 <0.10.0'
transformers:
- web_components:
    entry_points:
    - web/index.html
    - tool/status.html
    #- web/chartjs_element/index.html TODO(zoechi) element not available #6
    - web/firebase_element/index.html
    - web/gold_cc_cvc_input/index.html
    - web/gold_cc_expiration_input/index.html
    - web/gold_cc_input/index.html
    - web/gold_email_input/index.html
    - web/gold_phone_input/index.html
    - web/gold_zip_input/index.html
    - web/google_analytics/index.html # TODO(zoechi) issues #7
    - web/google_apis/index.html
    - web/google_calendar/index.html # TODO(zoechi) issues #7
    - web/google_castable_video/index.html # TODO(zoechi) issues #8
    - web/google_chart/index.html # TODO(zoechi) issues #9
    #- web/google_domain_user_picker/index.html TODO(zoechi) element not available #6
    #- web/google_drive/index.html TODO(zoechi) element not available #6
    - web/google_feeds/index.html
    - web/google_hangout_button/index.html
    - web/google_map/index.html
    - web/google_map/poly.html
    #- web/google_recaptcha/index.html # TODO(zoechi) element not available #6
    - web/google_sheets/index.html
    - web/google_signin/index.html # TODO(zoechi) issues #7
    - web/google_streetview_pano/index.html
    - web/google_url_shortener/index.html
    - web/google_youtube/index.html
    - web/google_youtube_upload/index.html
    - web/iron_a11y_announcer/index.html
    - web/iron_a11y_keys/index.html
    - web/iron_a11y_keys_behavior/index.html # TODO(zoechi) issues #10
    - web/iron_ajax/index.html
    - web/iron_autogrow_textarea/index.html
    - web/iron_behaviors/index.html
    - web/iron_checked_element_behavior/index.html
    - web/iron_collapse/index.html
    - web/iron_component_page/index.html # TODO(zoechi) json file can't be loaded when run without `pub serve`, some path issue #11
    - web/iron_doc_viewer/index.html
    - web/iron_dropdown/index.html # TODO(zoechi) doesn't work (position is off), I don't know how to port code in `expand_animation.dart` #12
    - web/iron_fit_behavior/index.html
    - web/iron_flex_layout/index.html
    - web/iron_form/index.html
    - web/iron_form_element_behavior/index.html
    - web/iron_icon/index.html
    - web/iron_icons/index.html
    - web/iron_iconset/index.html
    - web/iron_iconset_svg/index.html
    - web/iron_image/index.html
    - web/iron_input/index.html
    - web/iron_jsonp_library/index.html
    # - web/iron_label/index.html # TODO(zoechi) element not available #6
    - web/iron_list/index.html # TODO(zoechi) items height wrong when demo is inside an element for 3 examples #13
    - web/iron_list/collapse.html # TODO(zoechi) #13
    - web/iron_list/external_content.html
    - web/iron_list/selection.html # TODO(zoechi) clicking an item also adds it again to selected, even when it was already added #13
    - web/iron_localstorage/index.html
    - web/iron_media_query/index.html
    - web/iron_menu_behavior/index.html
    - web/iron_meta/index.html
    - web/iron_overlay_behavior/index.html
    - web/iron_pages/index.html
    - web/iron_range_behavior/index.html
    - web/iron_resizable_behavior/index.html
    - web/iron_selector/index.html
    - web/iron_signals/index.html
    - web/iron_validatable_behavior/index.html
    - web/iron_validator_behavior/index.html
    - web/marked_element/index.html
    #- web/neon_animation/card/index.html # TODO(zoechi) #28
    #- web/neon_animation/declarative/index.html # TODO(zoechi) #28
    #- web/neon_animation/doc/index.html # TODO(zoechi) #28
    #- web/neon_animation/dropdown/index.html # TODO(zoechi) #28
    #- web/neon_animation/grid/index.html # TODO(zoechi) #28
    #- web/neon_animation/list/index.html # TODO(zoechi) #28
    #- web/neon_animation/load/index.html # TODO(zoechi) #28
    #- web/neon_animation/reprojection/index.html # TODO(zoechi) #28
    #- web/neon_animation/tiles/index.html # TODO(zoechi) #28
    - web/paper_badge/index.html
    # - web/paper_behaviors/index.html # TODO(zoechi) #15
    - web/paper_button/index.html
    - web/paper_card/index.html
    - web/paper_checkbox/index.html
    - web/paper_dialog/index.html
    - web/paper_dialog_behavior/index.html
    - web/paper_dialog_scrollable/index.html
    - web/paper_drawer_panel/index.html
    - web/paper_dropdown_menu/index.html
    - web/paper_fab/index.html
    - web/paper_header_panel/index.html
    - web/paper_input/index.html
    - web/paper_icon_button/index.html
    - web/paper_item/index.html
    #- web/paper_listbox/index.html # TODO(zoechi) element not available #6
    - web/paper_material/index.html
    - web/paper_menu/index.html
    - web/paper_menu_button/index.html
    - web/paper_progress/index.html
    - web/paper_radio_button/index.html
    - web/paper_radio_group/index.html
    - web/paper_ripple/index.html
    - web/paper_scroll_header_panel/index.html # TODO(zoechi) demos 1-10 #27
    - web/paper_slider/index.html # TODO(zoechi) dart-lang/polymer_elements#74
    - web/paper_spinner/index.html
    - web/paper_styles/index.html
    - web/paper_tabs/index.html
    - web/paper_toast/index.html # TODO(zoechi) shown mostly behind left drawer in all-demos #26
    - web/paper_toggle_button/index.html # TODO(zoechi) labels are now show. I'll check again after a new versions of the elements is available
    - web/paper_toolbar/index.html
    - web/paper_tooltip/index.html # TODO(zoechi) rich text tooltips location wrong
    #- web/prism_element/index.html TODO(zoechi) JS demo doesn't seem to fully work yet, and it's not online
    #- web/platinum_bluetooth/index.html # TODO(zoechi) element not available #6
    #- web/platinum_https_redirect/index.html # TODO(zoechi) element not available #6
    #- web/platinum_push_messaging/index.html # TODO(zoechi) element not available #6
    #- web/platinum_sw/index.html # TODO(zoechi) element not available #6
    #- web/quick_element/index.html # TODO(zoechi) element not available #6
    #- web/seed_element/index.html # TODO(zoechi) element not available #6

- reflectable:
    entry_points:
    - web/index.dart
    - tool/status.dart
    #- web/chartjs_element/index.dart
    - web/firebase_element/index.dart
    - web/gold_cc_cvc_input/index.dart
    - web/gold_cc_expiration_input/index.dart
    - web/gold_cc_input/index.dart
    - web/gold_email_input/index.dart
    - web/gold_phone_input/index.dart
    - web/gold_zip_input/index.dart
    - web/google_analytics/index.dart
    - web/google_apis/index.dart
    - web/google_calendar/index.dart
    - web/google_castable_video/index.dart
    - web/google_chart/index.dart
    #- web/google_domain_user_picker/index.dart
    #- web/google_drive/index.dart
    - web/google_feeds/index.dart
    - web/google_hangout_button/index.dart
    - web/google_map/index.dart
    - web/google_map/poly.dart
    #- web/google_recaptcha/index.dart
    - web/google_sheets/index.dart
    - web/google_signin/index.dart
    - web/google_streetview_pano/index.dart
    - web/google_url_shortener/index.dart
    - web/google_youtube/index.dart
    - web/google_youtube_upload/index.dart
    - web/iron_a11y_announcer/index.dart
    - web/iron_a11y_keys/index.dart
    - web/iron_a11y_keys_behavior/index.dart
    - web/iron_ajax/index.dart
    - web/iron_autogrow_textarea/index.dart
    - web/iron_behaviors/index.dart
    - web/iron_checked_element_behavior/index.dart
    - web/iron_collapse/index.dart
    - web/iron_component_page/index.dart
    - web/iron_doc_viewer/index.dart
    - web/iron_dropdown/index.dart
    - web/iron_fit_behavior/index.dart
    - web/iron_flex_layout/index.dart
    - web/iron_form/index.dart
    - web/iron_form_element_behavior/index.dart
    - web/iron_icon/index.dart
    - web/iron_icons/index.dart
    - web/iron_iconset/index.dart
    - web/iron_iconset_svg/index.dart
    - web/iron_image/index.dart
    - web/iron_input/index.dart
    - web/iron_jsonp_library/index.dart
    # - web/iron_label/index.dart
    - web/iron_list/index.dart
    - web/iron_list/collapse.dart
    - web/iron_list/external_content.dart
    - web/iron_list/selection.dart
    - web/iron_localstorage/index.dart
    - web/iron_media_query/index.dart
    - web/iron_menu_behavior/index.dart
    - web/iron_meta/index.dart
    - web/iron_overlay_behavior/index.dart
    - web/iron_pages/index.dart
    - web/iron_range_behavior/index.dart
    - web/iron_resizable_behavior/index.dart
    - web/iron_selector/index.dart
    - web/iron_signals/index.dart
    - web/iron_validatable_behavior/index.dart
    - web/iron_validator_behavior/index.dart
    - web/marked_element/index.dart
    #- web/neon_animation/card/index.dart
    #- web/neon_animation/declarative/index.dart
    #- web/neon_animation/doc/index.dart
    #- web/neon_animation/dropdown/index.dart
    #- web/neon_animation/grid/index.dart
    #- web/neon_animation/list/index.dart
    #- web/neon_animation/load/index.dart
    #- web/neon_animation/reprojection/index.dart
    #- web/neon_animation/tiles/index.dart
    - web/paper_badge/index.dart
    #- web/paper_behaviors/index.dart
    - web/paper_button/index.dart
    - web/paper_card/index.dart
    - web/paper_checkbox/index.dart
    - web/paper_dialog/index.dart
    - web/paper_dialog_behavior/index.dart
    - web/paper_dialog_scrollable/index.dart
    - web/paper_drawer_panel/index.dart
    - web/paper_dropdown_menu/index.dart
    - web/paper_fab/index.dart
    - web/paper_header_panel/index.dart
    - web/paper_icon_button/index.dart
    - web/paper_input/index.dart
    - web/paper_item/index.dart
    - web/paper_listbox/index.dart
    - web/paper_material/index.dart
    - web/paper_menu/index.dart
    - web/paper_menu_button/index.dart
    - web/paper_progress/index.dart
    - web/paper_radio_button/index.dart
    - web/paper_radio_group/index.dart
    - web/paper_ripple/index.dart
    - web/paper_scroll_header_panel/index.dart
    - web/paper_slider/index.dart
    - web/paper_spinner/index.dart
    - web/paper_styles/index.dart
    - web/paper_tabs/index.dart
    - web/paper_toast/index.dart
    - web/paper_toggle_button/index.dart
    - web/paper_toolbar/index.dart
    - web/paper_tooltip/index.dart
    #- web/prism_element/index.dart
    #- web/platinum_bluetooth/index.dart
    #- web/platinum_https_redirect/index.dart
    #- web/platinum_push_messaging/index.dart
    #- web/platinum_sw/index.dart
    #- web/quick_element/index.dart
    #- web/seed_element/index.dart

- test/pub_serve:
    $include: test/**_test{.*,}.dart
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    commandLineOptions: ['--trust-type-annotations', '--trust-primitives']
